BitmasksPointers:
	table_width 2, BitmasksPointers
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw HonedgeBitmasks
	dw DoubladeBitmasks
	dw AegislashBitmasks
	dw StarlyBitmasks
	dw StaraviaBitmasks
	dw StaraptorBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw RotomBitmasks
	dw PoltegeistBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw PawniardBitmasks
	dw BisharpBitmasks
	dw RegigigasBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw LarvestaBitmasks
	dw VolcaronaBitmasks
	dw ArctozoltBitmasks
	dw ArctovishBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MamoswineBitmasks
	dw ElectivireBitmasks
	dw MagnezoneBitmasks
	dw YanmegaBitmasks
	dw GliscorBitmasks
	dw FerroseedBitmasks
	dw FerrothornBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw SolosisBitmasks
	dw DuosionBitmasks
	dw ReuniclusBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw WeavileBitmasks
	dw RhyperiorBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw MagmortarBitmasks
	dw HonchkrowBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw GardevoirBitmasks
	dw GaladeBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw DarkraiBitmasks
	dw MewBitmasks
	dw TreeckoBitmasks
	dw GrovyleBitmasks
	dw SceptileBitmasks
	dw ChimcharBitmasks
	dw MonfernoBitmasks
	dw InfernapeBitmasks
	dw FroakieBitmasks
	dw FrogadierBitmasks
	dw GreninjaBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw VoltikBitmasks
	dw GalvantulaBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw SigilyphBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw SylveonBitmasks
	dw MismagiusBitmasks
	dw PorygonzBitmasks
	dw GenesectBitmasks
	dw PolitoedBitmasks
	dw TimburrBitmasks
	dw GurdurrBitmasks
	dw ConkeldurrBitmasks
	dw BeldumBitmasks
	dw MetangBitmasks
	dw MetagrossBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw GibleBitmasks
	dw GabiteBitmasks
	dw GarchompBitmasks
	dw ScizorBitmasks
	dw ShayminBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw LatiasBitmasks
	dw DeoxysBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw SpiritombBitmasks
	dw LatiosBitmasks
	dw PalkiaBitmasks
	dw KyogreBitmasks
	dw GroudonBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw CottoneeBitmasks
	dw WhimsicottBitmasks
	dw Porygon2Bitmasks
	dw RayquazaBitmasks
	dw SmeargleBitmasks
	dw DialgaBitmasks
	dw KlefkiBitmasks
	dw XerneasBitmasks
	dw YveltalBitmasks
	dw GiratinaBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw MewtwoBitmasks
	dw ArceusBitmasks
	assert_table_length NUM_POKEMON
