BitmasksPointers:
	table_width 2, BitmasksPointers
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataBitmasks
	dw RaticateBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw SandshrewBitmasks
	dw SandslashBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw LarvestaBitmasks
	dw VolcaronaBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw FarfetchDBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw CuboneBitmasks
	dw MarowakBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw DarkraiBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw ChandelureBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw TogekissBitmasks
	dw SigilyphBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MismagiusBitmasks
	dw PorygonzBitmasks
	dw GenesectBitmasks
	dw PolitoedBitmasks
	dw TimburrBitmasks
	dw GurdurrBitmasks
	dw ConkeldurrBitmasks
	dw BeldumBitmasks
	dw MetangBitmasks
	dw MetagrossBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw GibleBitmasks
	dw GabiteBitmasks
	dw GarchompBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw LatiasBitmasks
	dw DeoxysBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw SpiritombBitmasks
	dw LatiosBitmasks
	dw PalkiaBitmasks
	dw KyogreBitmasks
	dw GroudonBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw RayquazaBitmasks
	dw SmeargleBitmasks
	dw DialgaBitmasks
	dw HitmontopBitmasks
	dw XerneasBitmasks
	dw YveltalBitmasks
	dw GiratinaBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw MewtwoBitmasks
	dw ArceusBitmasks
	assert_table_length NUM_POKEMON
