AnimationIdlePointers:
	table_width 2, AnimationIdlePointers
	dw BulbasaurAnimationIdle
	dw IvysaurAnimationIdle
	dw VenusaurAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw CaterpieAnimationIdle
	dw MetapodAnimationIdle
	dw ButterfreeAnimationIdle
	dw HonedgeAnimationIdle
	dw DoubladeAnimationIdle
	dw AegislashAnimationIdle
	dw StarlyAnimationIdle
	dw StaraviaAnimationIdle
	dw StaraptorAnimationIdle
	dw RattataAnimationIdle
	dw RaticateAnimationIdle
	dw BunearyAnimationIdle
	dw LopunnyAnimationIdle
	dw EkansAnimationIdle
	dw ArbokAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw RotomAnimationIdle
	dw PoltegeistAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw VulpixAnimationIdle
	dw NinetalesAnimationIdle
	dw JigglypuffAnimationIdle
	dw WigglytuffAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw PawniardAnimationIdle
	dw BisharpAnimationIdle
	dw RegigigasAnimationIdle
	dw ZygardeAnimationIdle
	dw HawluchaAnimationIdle
	dw LarvestaAnimationIdle
	dw VolcaronaAnimationIdle
	dw ArctozoltAnimationIdle
	dw ArctovishAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw PsyduckAnimationIdle
	dw GolduckAnimationIdle
	dw ShroomishAnimationIdle
	dw BreloomAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw PoliwagAnimationIdle
	dw PoliwhirlAnimationIdle
	dw PoliwrathAnimationIdle
	dw AbraAnimationIdle
	dw KadabraAnimationIdle
	dw AlakazamAnimationIdle
	dw MachopAnimationIdle
	dw MachokeAnimationIdle
	dw MachampAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw GeodudeAnimationIdle
	dw GravelerAnimationIdle
	dw GolemAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw MamoswineAnimationIdle
	dw ElectivireAnimationIdle
	dw MagnezoneAnimationIdle
	dw YanmegaAnimationIdle
	dw GliscorAnimationIdle
	dw FerroseedAnimationIdle
	dw FerrothornAnimationIdle
	dw ShellderAnimationIdle
	dw CloysterAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw FeebasAnimationIdle
	dw MiloticAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw ExeggcuteAnimationIdle
	dw ExeggutorAnimationIdle
	dw CuboneAnimationIdle
	dw MarowakAnimationIdle
	dw SolosisAnimationIdle
	dw DuosionAnimationIdle
	dw ReuniclusAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw ChanseyAnimationIdle
	dw WeavileAnimationIdle
	dw RhyperiorAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw MagmortarAnimationIdle
	dw HonchkrowAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw RaltsAnimationIdle
	dw KirliaAnimationIdle
	dw GardevoirAnimationIdle
	dw GaladeAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw DarkraiAnimationIdle
	dw MewAnimationIdle
	dw TreeckoAnimationIdle
	dw GrovyleAnimationIdle
	dw SceptileAnimationIdle
	dw ChimcharAnimationIdle
	dw MonfernoAnimationIdle
	dw InfernapeAnimationIdle
	dw FroakieAnimationIdle
	dw FrogadierAnimationIdle
	dw GreninjaAnimationIdle
	dw RioluAnimationIdle
	dw LucarioAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw DrilburAnimationIdle
	dw ExcadrillAnimationIdle
	dw VoltikAnimationIdle
	dw GalvantulaAnimationIdle
	dw CrobatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw LitwickAnimationIdle
	dw LampentAnimationIdle
	dw ChandelureAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw TogekissAnimationIdle
	dw SigilyphAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw SylveonAnimationIdle
	dw MismagiusAnimationIdle
	dw PorygonzAnimationIdle
	dw GenesectAnimationIdle
	dw PolitoedAnimationIdle
	dw TimburrAnimationIdle
	dw GurdurrAnimationIdle
	dw ConkeldurrAnimationIdle
	dw BeldumAnimationIdle
	dw MetangAnimationIdle
	dw MetagrossAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw MurkrowAnimationIdle
	dw SlowkingAnimationIdle
	dw MisdreavusAnimationIdle
	dw UnownAnimationIdle
	dw WobbuffetAnimationIdle
	dw BagonAnimationIdle
	dw ShelgonAnimationIdle
	dw SalamenceAnimationIdle
	dw DunsparceAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw GibleAnimationIdle
	dw GabiteAnimationIdle
	dw GarchompAnimationIdle
	dw ScizorAnimationIdle
	dw ShayminAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw LatiasAnimationIdle
	dw DeoxysAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw SpiritombAnimationIdle
	dw LatiosAnimationIdle
	dw PalkiaAnimationIdle
	dw KyogreAnimationIdle
	dw GroudonAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw CottoneeAnimationIdle
	dw WhimsicottAnimationIdle
	dw Porygon2AnimationIdle
	dw RayquazaAnimationIdle
	dw SmeargleAnimationIdle
	dw DialgaAnimationIdle
	dw KlefkiAnimationIdle
	dw XerneasAnimationIdle
	dw YveltalAnimationIdle
	dw GiratinaAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	dw MewtwoAnimationIdle
	dw ArceusAnimationIdle
	assert_table_length NUM_POKEMON
