const fs = require("fs-extra");
const path = require("path");
var regexStatus =
  /db[\s]+[0-9]+,[\s]+[0-9]+,[\s]+[0-9]+,[\s]+[0-9]+,[\s]+[0-9]+,[\s]+[0-9]+/;

var statusString = ["hp", "atk", "def", "spd", "sat", "sdf"];

var pokemonList = [
  "abra.asm",
  "aerodactyl.asm",
  "aipom.asm",
  "alakazam.asm",
  "ampharos.asm",
  "arbok.asm",
  "arcanine.asm",
  "ariados.asm",
  "articuno.asm",
  "azumarill.asm",
  "bayleef.asm",
  "beedrill.asm",
  "bellossom.asm",
  "bellsprout.asm",
  "blastoise.asm",
  "blissey.asm",
  "bulbasaur.asm",
  "butterfree.asm",
  "caterpie.asm",
  "celebi.asm",
  "chansey.asm",
  "charizard.asm",
  "charmander.asm",
  "charmeleon.asm",
  "chikorita.asm",
  "chinchou.asm",
  "clefable.asm",
  "clefairy.asm",
  "cleffa.asm",
  "cloyster.asm",
  "corsola.asm",
  "crobat.asm",
  "croconaw.asm",
  "cubone.asm",
  "cyndaquil.asm",
  "delibird.asm",
  "dewgong.asm",
  "diglett.asm",
  "ditto.asm",
  "dodrio.asm",
  "doduo.asm",
  "donphan.asm",
  "dragonair.asm",
  "dragonite.asm",
  "dratini.asm",
  "drowzee.asm",
  "dugtrio.asm",
  "dunsparce.asm",
  "eevee.asm",
  "ekans.asm",
  "electabuzz.asm",
  "electrode.asm",
  "elekid.asm",
  "entei.asm",
  "espeon.asm",
  "exeggcute.asm",
  "exeggutor.asm",
  "farfetch_d.asm",
  "fearow.asm",
  "feraligatr.asm",
  "flaaffy.asm",
  "flareon.asm",
  "forretress.asm",
  "furret.asm",
  "gastly.asm",
  "gengar.asm",
  "geodude.asm",
  "girafarig.asm",
  "gligar.asm",
  "gloom.asm",
  "golbat.asm",
  "goldeen.asm",
  "golduck.asm",
  "golem.asm",
  "granbull.asm",
  "graveler.asm",
  "grimer.asm",
  "growlithe.asm",
  "gyarados.asm",
  "haunter.asm",
  "heracross.asm",
  "hitmonchan.asm",
  "hitmonlee.asm",
  "hitmontop.asm",
  "ho_oh.asm",
  "hoothoot.asm",
  "hoppip.asm",
  "horsea.asm",
  "houndoom.asm",
  "houndour.asm",
  "hypno.asm",
  "igglybuff.asm",
  "ivysaur.asm",
  "jigglypuff.asm",
  "jolteon.asm",
  "jumpluff.asm",
  "jynx.asm",
  "kabuto.asm",
  "kabutops.asm",
  "kadabra.asm",
  "kakuna.asm",
  "kangaskhan.asm",
  "kingdra.asm",
  "kingler.asm",
  "koffing.asm",
  "krabby.asm",
  "lanturn.asm",
  "lapras.asm",
  "larvitar.asm",
  "ledian.asm",
  "ledyba.asm",
  "lickitung.asm",
  "lugia.asm",
  "machamp.asm",
  "machoke.asm",
  "machop.asm",
  "magby.asm",
  "magcargo.asm",
  "magikarp.asm",
  "magmar.asm",
  "magnemite.asm",
  "magneton.asm",
  "mankey.asm",
  "mantine.asm",
  "mareep.asm",
  "marill.asm",
  "marowak.asm",
  "meganium.asm",
  "meowth.asm",
  "metapod.asm",
  "mew.asm",
  "mewtwo.asm",
  "miltank.asm",
  "misdreavus.asm",
  "moltres.asm",
  "mr__mime.asm",
  "muk.asm",
  "murkrow.asm",
  "natu.asm",
  "nidoking.asm",
  "nidoqueen.asm",
  "nidoran_f.asm",
  "nidoran_m.asm",
  "nidorina.asm",
  "nidorino.asm",
  "ninetales.asm",
  "noctowl.asm",
  "octillery.asm",
  "oddish.asm",
  "omanyte.asm",
  "omastar.asm",
  "onix.asm",
  "paras.asm",
  "parasect.asm",
  "persian.asm",
  "phanpy.asm",
  "pichu.asm",
  "pidgeot.asm",
  "pidgeotto.asm",
  "pidgey.asm",
  "pikachu.asm",
  "piloswine.asm",
  "pineco.asm",
  "pinsir.asm",
  "politoed.asm",
  "poliwag.asm",
  "poliwhirl.asm",
  "poliwrath.asm",
  "ponyta.asm",
  "porygon.asm",
  "porygon2.asm",
  "primeape.asm",
  "psyduck.asm",
  "pupitar.asm",
  "quagsire.asm",
  "quilava.asm",
  "qwilfish.asm",
  "raichu.asm",
  "raikou.asm",
  "rapidash.asm",
  "raticate.asm",
  "rattata.asm",
  "remoraid.asm",
  "rhydon.asm",
  "rhyhorn.asm",
  "sandshrew.asm",
  "sandslash.asm",
  "scizor.asm",
  "scyther.asm",
  "seadra.asm",
  "seaking.asm",
  "seel.asm",
  "sentret.asm",
  "shellder.asm",
  "shuckle.asm",
  "skarmory.asm",
  "skiploom.asm",
  "slowbro.asm",
  "slowking.asm",
  "slowpoke.asm",
  "slugma.asm",
  "smeargle.asm",
  "smoochum.asm",
  "sneasel.asm",
  "snorlax.asm",
  "snubbull.asm",
  "spearow.asm",
  "spinarak.asm",
  "squirtle.asm",
  "stantler.asm",
  "starmie.asm",
  "staryu.asm",
  "steelix.asm",
  "sudowoodo.asm",
  "suicune.asm",
  "sunflora.asm",
  "sunkern.asm",
  "swinub.asm",
  "tangela.asm",
  "tauros.asm",
  "teddiursa.asm",
  "tentacool.asm",
  "tentacruel.asm",
  "togepi.asm",
  "togetic.asm",
  "totodile.asm",
  "typhlosion.asm",
  "tyranitar.asm",
  "tyrogue.asm",
  "umbreon.asm",
  "unown.asm",
  "ursaring.asm",
  "vaporeon.asm",
  "venomoth.asm",
  "venonat.asm",
  "venusaur.asm",
  "victreebel.asm",
  "vileplume.asm",
  "voltorb.asm",
  "vulpix.asm",
  "wartortle.asm",
  "weedle.asm",
  "weepinbell.asm",
  "weezing.asm",
  "wigglytuff.asm",
  "wobbuffet.asm",
  "wooper.asm",
  "xatu.asm",
  "yanma.asm",
  "zapdos.asm",
  "zubat.asm",
];

var pokemonName = {
  bulbasaur: ["#001", "妙蛙種子", "フシギダネ", "bulbasaur"],
  ivysaur: ["#002", "妙蛙草", "フシギソウ", "ivysaur"],
  venusaur: ["#003", "妙蛙花", "フシギバナ", "venusaur"],
  charmander: ["#004", "小火龍", "ヒトカゲ", "charmander"],
  charmeleon: ["#005", "火恐龍", "リザード", "charmeleon"],
  charizard: ["#006", "噴火龍", "リザードン", "charizard"],
  squirtle: ["#007", "傑尼龜", "ゼニガメ", "squirtle"],
  wartortle: ["#008", "卡咪龜", "カメール", "wartortle"],
  blastoise: ["#009", "水箭龜", "カメックス", "blastoise"],
  caterpie: ["#010", "綠毛蟲", "キャタピー", "caterpie"],
  metapod: ["#011", "鐵甲蛹", "トランセル", "metapod"],
  butterfree: ["#012", "巴大蝶", "バタフリー", "butterfree"],
  weedle: ["#013", "獨角蟲", "ビードル", "weedle"],
  kakuna: ["#014", "鐵殼蛹", "コクーン", "kakuna"],
  beedrill: ["#015", "大針蜂", "スピアー", "beedrill"],
  pidgey: ["#016", "波波", "ポッポ", "pidgey"],
  pidgeotto: ["#017", "比比鳥", "ピジョン", "pidgeotto"],
  pidgeot: ["#018", "大比鳥", "ピジョット", "pidgeot"],
  rattata: ["#019", "小拉達", "コラッタ", "rattata"],
  raticate: ["#020", "拉達", "ラッタ", "raticate"],
  spearow: ["#021", "烈雀", "オニスズメ", "spearow"],
  fearow: ["#022", "大嘴雀", "オニドリル", "fearow"],
  ekans: ["#023", "阿柏蛇", "アーボ", "ekans"],
  arbok: ["#024", "阿柏怪", "アーボック", "arbok"],
  pikachu: ["#025", "皮卡丘", "ピカチュウ", "pikachu"],
  raichu: ["#026", "雷丘", "ライチュウ", "raichu"],
  sandshrew: ["#027", "穿山鼠", "サンド", "sandshrew"],
  sandslash: ["#028", "穿山王", "サンドパン", "sandslash"],
  "nidoran♀": ["#029", "尼多蘭", "ニドラン♀", "nidoran♀"],
  nidorina: ["#030", "尼多娜", "ニドリーナ", "nidorina"],
  nidoqueen: ["#031", "尼多后", "ニドクイン", "nidoqueen"],
  "nidoran♂": ["#032", "尼多朗", "ニドラン♂", "nidoran♂"],
  nidorino: ["#033", "尼多力諾", "ニドリーノ", "nidorino"],
  nidoking: ["#034", "尼多王", "ニドキング", "nidoking"],
  clefairy: ["#035", "皮皮", "ピッピ", "clefairy"],
  clefable: ["#036", "皮可西", "ピクシー", "clefable"],
  vulpix: ["#037", "六尾", "ロコン", "vulpix"],
  ninetales: ["#038", "九尾", "キュウコン", "ninetales"],
  jigglypuff: ["#039", "胖丁", "プリン", "jigglypuff"],
  wigglytuff: ["#040", "胖可丁", "プクリン", "wigglytuff"],
  zubat: ["#041", "超音蝠", "ズバット", "zubat"],
  golbat: ["#042", "大嘴蝠", "ゴルバット", "golbat"],
  oddish: ["#043", "走路草", "ナゾノクサ", "oddish"],
  gloom: ["#044", "臭臭花", "クサイハナ", "gloom"],
  vileplume: ["#045", "霸王花", "ラフレシア", "vileplume"],
  paras: ["#046", "派拉斯", "パラス", "paras"],
  parasect: ["#047", "派拉斯特", "パラセクト", "parasect"],
  venonat: ["#048", "毛球", "コンパン", "venonat"],
  venomoth: ["#049", "摩魯蛾", "モルフォン", "venomoth"],
  diglett: ["#050", "地鼠", "ディグダ", "diglett"],
  dugtrio: ["#051", "三地鼠", "ダグトリオ", "dugtrio"],
  meowth: ["#052", "喵喵", "ニャース", "meowth"],
  persian: ["#053", "貓老大", "ペルシアン", "persian"],
  psyduck: ["#054", "可達鴨", "コダック", "psyduck"],
  golduck: ["#055", "哥達鴨", "ゴルダック", "golduck"],
  mankey: ["#056", "猴怪", "マンキー", "mankey"],
  primeape: ["#057", "火爆猴", "オコリザル", "primeape"],
  growlithe: ["#058", "卡蒂狗", "ガーディ", "growlithe"],
  arcanine: ["#059", "風速狗", "ウインディ", "arcanine"],
  poliwag: ["#060", "蚊香蝌蚪", "ニョロモ", "poliwag"],
  poliwhirl: ["#061", "蚊香君", "ニョロゾ", "poliwhirl"],
  poliwrath: ["#062", "蚊香泳士", "ニョロボン", "poliwrath"],
  abra: ["#063", "凱西", "ケーシィ", "abra"],
  kadabra: ["#064", "勇基拉", "ユンゲラー", "kadabra"],
  alakazam: ["#065", "胡地", "フーディン", "alakazam"],
  machop: ["#066", "腕力", "ワンリキー", "machop"],
  machoke: ["#067", "豪力", "ゴーリキー", "machoke"],
  machamp: ["#068", "怪力", "カイリキー", "machamp"],
  bellsprout: ["#069", "喇叭芽", "マダツボミ", "bellsprout"],
  weepinbell: ["#070", "口呆花", "ウツドン", "weepinbell"],
  victreebel: ["#071", "大食花", "ウツボット", "victreebel"],
  tentacool: ["#072", "瑪瑙水母", "メノクラゲ", "tentacool"],
  tentacruel: ["#073", "毒刺水母", "ドククラゲ", "tentacruel"],
  geodude: ["#074", "小拳石", "イシツブテ", "geodude"],
  graveler: ["#075", "隆隆石", "ゴローン", "graveler"],
  golem: ["#076", "隆隆岩", "ゴローニャ", "golem"],
  ponyta: ["#077", "小火馬", "ポニータ", "ponyta"],
  rapidash: ["#078", "烈焰馬", "ギャロップ", "rapidash"],
  slowpoke: ["#079", "呆呆獸", "ヤドン", "slowpoke"],
  slowbro: ["#080", "呆殼獸", "ヤドラン", "slowbro"],
  magnemite: ["#081", "小磁怪", "コイル", "magnemite"],
  magneton: ["#082", "三合一磁怪", "レアコイル", "magneton"],
  farfetch: ["#083", "大蔥鴨", "カモネギ", "farfetch"],
  doduo: ["#084", "嘟嘟", "ドードー", "doduo"],
  dodrio: ["#085", "嘟嘟利", "ドードリオ", "dodrio"],
  seel: ["#086", "小海獅", "パウワウ", "seel"],
  dewgong: ["#087", "白海獅", "ジュゴン", "dewgong"],
  grimer: ["#088", "臭泥", "ベトベター", "grimer"],
  muk: ["#089", "臭臭泥", "ベトベトン", "muk"],
  shellder: ["#090", "大舌貝", "シェルダー", "shellder"],
  cloyster: ["#091", "刺甲貝", "パルシェン", "cloyster"],
  gastly: ["#092", "鬼斯", "ゴース", "gastly"],
  haunter: ["#093", "鬼斯通", "ゴースト", "haunter"],
  gengar: ["#094", "耿鬼", "ゲンガー", "gengar"],
  onix: ["#095", "大岩蛇", "イワーク", "onix"],
  drowzee: ["#096", "催眠貘", "スリープ", "drowzee"],
  hypno: ["#097", "引夢貘人", "スリーパー", "hypno"],
  krabby: ["#098", "大鉗蟹", "クラブ", "krabby"],
  kingler: ["#099", "巨鉗蟹", "キングラー", "kingler"],
  voltorb: ["#100", "霹靂電球", "ビリリダマ", "voltorb"],
  electrode: ["#101", "頑皮雷彈", "マルマイン", "electrode"],
  exeggcute: ["#102", "蛋蛋", "タマタマ", "exeggcute"],
  exeggutor: ["#103", "椰蛋樹", "ナッシー", "exeggutor"],
  cubone: ["#104", "卡拉卡拉", "カラカラ", "cubone"],
  marowak: ["#105", "嘎啦嘎啦", "ガラガラ", "marowak"],
  hitmonlee: ["#106", "飛腿郎", "サワムラー", "hitmonlee"],
  hitmonchan: ["#107", "快拳郎", "エビワラー", "hitmonchan"],
  lickitung: ["#108", "大舌頭", "ベロリンガ", "lickitung"],
  koffing: ["#109", "瓦斯彈", "ドガース", "koffing"],
  weezing: ["#110", "雙彈瓦斯", "マタドガス", "weezing"],
  rhyhorn: ["#111", "獨角犀牛", "サイホーン", "rhyhorn"],
  rhydon: ["#112", "鑽角犀獸", "サイドン", "rhydon"],
  chansey: ["#113", "吉利蛋", "ラッキー", "chansey"],
  tangela: ["#114", "蔓藤怪", "モンジャラ", "tangela"],
  kangaskhan: ["#115", "袋獸", "ガルーラ", "kangaskhan"],
  horsea: ["#116", "墨海馬", "タッツー", "horsea"],
  seadra: ["#117", "海刺龍", "シードラ", "seadra"],
  goldeen: ["#118", "角金魚", "トサキント", "goldeen"],
  seaking: ["#119", "金魚王", "アズマオウ", "seaking"],
  staryu: ["#120", "海星星", "ヒトデマン", "staryu"],
  starmie: ["#121", "寶石海星", "スターミー", "starmie"],
  mime: ["#122", "魔牆人偶", "バリヤード", "mr. mime"],
  scyther: ["#123", "飛天螳螂", "ストライク", "scyther"],
  jynx: ["#124", "迷唇姐", "ルージュラ", "jynx"],
  electabuzz: ["#125", "電擊獸", "エレブー", "electabuzz"],
  magmar: ["#126", "鴨嘴火獸", "ブーバー", "magmar"],
  pinsir: ["#127", "凱羅斯", "カイロス", "pinsir"],
  tauros: ["#128", "肯泰羅", "ケンタロス", "tauros"],
  magikarp: ["#129", "鯉魚王", "コイキング", "magikarp"],
  gyarados: ["#130", "暴鯉龍", "ギャラドス", "gyarados"],
  lapras: ["#131", "拉普拉斯", "ラプラス", "lapras"],
  ditto: ["#132", "百變怪", "メタモン", "ditto"],
  eevee: ["#133", "伊布", "イーブイ", "eevee"],
  vaporeon: ["#134", "水伊布", "シャワーズ", "vaporeon"],
  jolteon: ["#135", "雷伊布", "サンダース", "jolteon"],
  flareon: ["#136", "火伊布", "ブースター", "flareon"],
  porygon: ["#137", "多邊獸", "ポリゴン", "porygon"],
  omanyte: ["#138", "菊石獸", "オムナイト", "omanyte"],
  omastar: ["#139", "多刺菊石獸", "オムスター", "omastar"],
  kabuto: ["#140", "化石盔", "カブト", "kabuto"],
  kabutops: ["#141", "鐮刀盔", "カブトプス", "kabutops"],
  aerodactyl: ["#142", "化石翼龍", "プテラ", "aerodactyl"],
  snorlax: ["#143", "卡比獸", "カビゴン", "snorlax"],
  articuno: ["#144", "急凍鳥", "フリーザー", "articuno"],
  zapdos: ["#145", "閃電鳥", "サンダー", "zapdos"],
  moltres: ["#146", "火焰鳥", "ファイヤー", "moltres"],
  dratini: ["#147", "迷你龍", "ミニリュウ", "dratini"],
  dragonair: ["#148", "哈克龍", "ハクリュー", "dragonair"],
  dragonite: ["#149", "快龍", "カイリュー", "dragonite"],
  mewtwo: ["#150", "超夢", "ミュウツー", "mewtwo"],
  mew: ["#151", "夢幻", "ミュウ", "mew"],
  chikorita: ["#152", "菊草葉", "チコリータ", "chikorita"],
  bayleef: ["#153", "月桂葉", "ベイリーフ", "bayleef"],
  meganium: ["#154", "大竺葵", "メガニウム", "meganium"],
  cyndaquil: ["#155", "火球鼠", "ヒノアラシ", "cyndaquil"],
  quilava: ["#156", "火岩鼠", "マグマラシ", "quilava"],
  typhlosion: ["#157", "火爆獸", "バクフーン", "typhlosion"],
  totodile: ["#158", "小鋸鱷", "ワニノコ", "totodile"],
  croconaw: ["#159", "藍鱷", "アリゲイツ", "croconaw"],
  feraligatr: ["#160", "大力鱷", "オーダイル", "feraligatr"],
  sentret: ["#161", "尾立", "オタチ", "sentret"],
  furret: ["#162", "大尾立", "オオタチ", "furret"],
  hoothoot: ["#163", "咕咕", "ホーホー", "hoothoot"],
  noctowl: ["#164", "貓頭夜鷹", "ヨルノズク", "noctowl"],
  ledyba: ["#165", "芭瓢蟲", "レディバ", "ledyba"],
  ledian: ["#166", "安瓢蟲", "レディアン", "ledian"],
  spinarak: ["#167", "圓絲蛛", "イトマル", "spinarak"],
  ariados: ["#168", "阿利多斯", "アリアドス", "ariados"],
  crobat: ["#169", "叉字蝠", "クロバット", "crobat"],
  chinchou: ["#170", "燈籠魚", "チョンチー", "chinchou"],
  lanturn: ["#171", "電燈怪", "ランターン", "lanturn"],
  pichu: ["#172", "皮丘", "ピチュー", "pichu"],
  cleffa: ["#173", "皮寶寶", "ピィ", "cleffa"],
  igglybuff: ["#174", "寶寶丁", "ププリン", "igglybuff"],
  togepi: ["#175", "波克比", "トゲピー", "togepi"],
  togetic: ["#176", "波克基古", "トゲチック", "togetic"],
  natu: ["#177", "天然雀", "ネイティ", "natu"],
  xatu: ["#178", "天然鳥", "ネイティオ", "xatu"],
  mareep: ["#179", "咩利羊", "メリープ", "mareep"],
  flaaffy: ["#180", "茸茸羊", "モココ", "flaaffy"],
  ampharos: ["#181", "電龍", "デンリュウ", "ampharos"],
  bellossom: ["#182", "美麗花", "キレイハナ", "bellossom"],
  marill: ["#183", "瑪力露", "マリル", "marill"],
  azumarill: ["#184", "瑪力露麗", "マリルリ", "azumarill"],
  sudowoodo: ["#185", "樹才怪", "ウソッキー", "sudowoodo"],
  politoed: ["#186", "蚊香蛙皇", "ニョロトノ", "politoed"],
  hoppip: ["#187", "毽子草", "ハネッコ", "hoppip"],
  skiploom: ["#188", "毽子花", "ポポッコ", "skiploom"],
  jumpluff: ["#189", "毽子棉", "ワタッコ", "jumpluff"],
  aipom: ["#190", "長尾怪手", "エイパム", "aipom"],
  sunkern: ["#191", "向日種子", "ヒマナッツ", "sunkern"],
  sunflora: ["#192", "向日花怪", "キマワリ", "sunflora"],
  yanma: ["#193", "蜻蜻蜓", "ヤンヤンマ", "yanma"],
  wooper: ["#194", "烏波", "ウパー", "wooper"],
  quagsire: ["#195", "沼王", "ヌオー", "quagsire"],
  espeon: ["#196", "太陽伊布", "エーフィ", "espeon"],
  umbreon: ["#197", "月亮伊布", "ブラッキー", "umbreon"],
  murkrow: ["#198", "黑暗鴉", "ヤミカラス", "murkrow"],
  slowking: ["#199", "呆呆王", "ヤドキング", "slowking"],
  misdreavus: ["#200", "夢妖", "ムウマ", "misdreavus"],
  unown: ["#201", "未知圖騰", "アンノーン", "unown"],
  wobbuffet: ["#202", "果然翁", "ソーナンス", "wobbuffet"],
  girafarig: ["#203", "麒麟奇", "キリンリキ", "girafarig"],
  pineco: ["#204", "榛果球", "クヌギダマ", "pineco"],
  forretress: ["#205", "佛烈托斯", "フォレトス", "forretress"],
  dunsparce: ["#206", "土龍弟弟", "ノコッチ", "dunsparce"],
  gligar: ["#207", "天蠍", "グライガー", "gligar"],
  steelix: ["#208", "大鋼蛇", "ハガネール", "steelix"],
  snubbull: ["#209", "布魯", "ブルー", "snubbull"],
  granbull: ["#210", "布魯皇", "グランブル", "granbull"],
  qwilfish: ["#211", "千針魚", "ハリーセン", "qwilfish"],
  scizor: ["#212", "巨鉗螳螂", "ハッサム", "scizor"],
  shuckle: ["#213", "壺壺", "ツボツボ", "shuckle"],
  heracross: ["#214", "赫拉克羅斯", "ヘラクロス", "heracross"],
  sneasel: ["#215", "狃拉", "ニューラ", "sneasel"],
  teddiursa: ["#216", "熊寶寶", "ヒメグマ", "teddiursa"],
  ursaring: ["#217", "圈圈熊", "リングマ", "ursaring"],
  slugma: ["#218", "熔岩蟲", "マグマッグ", "slugma"],
  magcargo: ["#219", "熔岩蝸牛", "マグカルゴ", "magcargo"],
  swinub: ["#220", "小山豬", "ウリムー", "swinub"],
  piloswine: ["#221", "長毛豬", "イノムー", "piloswine"],
  corsola: ["#222", "太陽珊瑚", "サニーゴ", "corsola"],
  remoraid: ["#223", "鐵炮魚", "テッポウオ", "remoraid"],
  octillery: ["#224", "章魚桶", "オクタン", "octillery"],
  delibird: ["#225", "信使鳥", "デリバード", "delibird"],
  mantine: ["#226", "巨翅飛魚", "マンタイン", "mantine"],
  skarmory: ["#227", "盔甲鳥", "エアームド", "skarmory"],
  houndour: ["#228", "戴魯比", "デルビル", "houndour"],
  houndoom: ["#229", "黑魯加", "ヘルガー", "houndoom"],
  kingdra: ["#230", "刺龍王", "キングドラ", "kingdra"],
  phanpy: ["#231", "小小象", "ゴマゾウ", "phanpy"],
  donphan: ["#232", "頓甲", "ドンファン", "donphan"],
  porygon2: ["#233", "多邊獸ⅱ", "ポリゴン２", "porygon2"],
  stantler: ["#234", "驚角鹿", "オドシシ", "stantler"],
  smeargle: ["#235", "圖圖犬", "ドーブル", "smeargle"],
  tyrogue: ["#236", "無畏小子", "バルキー", "tyrogue"],
  hitmontop: ["#237", "戰舞郎", "カポエラー", "hitmontop"],
  smoochum: ["#238", "迷唇娃", "ムチュール", "smoochum"],
  elekid: ["#239", "電擊怪", "エレキッド", "elekid"],
  magby: ["#240", "鴨嘴寶寶", "ブビィ", "magby"],
  miltank: ["#241", "大奶罐", "ミルタンク", "miltank"],
  blissey: ["#242", "幸福蛋", "ハピナス", "blissey"],
  raikou: ["#243", "雷公", "ライコウ", "raikou"],
  entei: ["#244", "炎帝", "エンテイ", "entei"],
  suicune: ["#245", "水君", "スイクン", "suicune"],
  larvitar: ["#246", "幼基拉斯", "ヨーギラス", "larvitar"],
  pupitar: ["#247", "沙基拉斯", "サナギラス", "pupitar"],
  tyranitar: ["#248", "班基拉斯", "バンギラス", "tyranitar"],
  lugia: ["#249", "洛奇亞", "ルギア", "lugia"],
  ho_oh: ["#250", "鳳王", "ホウオウ", "ho_oh"],
  celebi: ["#251", "時拉比", "セレビィ", "celebi"],
};

class Countor {
  constructor() {
    this.allLoad();
  }

  async allLoad() {
    var _list = [];
    for (let index = 0; index < pokemonList.length; index++) {
      const fileName = pokemonList[index];
      let fileContent = await this.load(fileName);
      let result = await this.parse(fileName, fileContent);

      _list.push(result);
    }
    await fs.ensureFile(
      path.join(process.cwd(), "tools", "node", "build", "data.json")
    );
    fs.writeJSON(
      path.join(process.cwd(), "tools", "node", "build", "data.json"),
      this.sort(_list),
      {
        spaces: 4,
      }
    );
  }

  async load(fileName) {
    let burf = await fs.readFile(
      path.join(process.cwd(), "data", "pokemon", "base_stats", fileName)
    );
    return burf.toString("utf8");
  }

  async parse(fileName, fileContent) {
    let result = regexStatus.exec(fileContent);

    if (result != null && result.length > 0) {
      let pokemon = {
        name: this.prepareName(fileName.replace(".asm", "")),
      };
      let statusArray = result[0]
        .replace(/db/g, "")
        .replace(/[^0-9\,]/, "")
        .split(",")
        .map((e) => +e.replace(/[\D]/g, ""));

      for (let i = 0; i < statusString.length; i++) {
        pokemon[statusString[i]] = statusArray[i];
      }
      pokemon["total"] = statusArray.map((a) => +a).reduce((a, b) => a + b);
      return pokemon;
      return;
    } else {
      console.log(result);
    }

    return `${fileName}`;
  }

  sort(list) {
    return [].concat(list).sort((a, b) => {
      return b.total - a.total;
    });
  }

  prepareName(rawName) {
    if (pokemonName[rawName] != null) {
      return pokemonName[rawName].join(" ");
    }
    return rawName;
  }
}

new Countor();
